import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore: side-effect import of CSS without type declarations
import "./globals.css";

import Sidebar from '@/components/Sidebar'
import Header from '@/components/Header'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div> <div className="flex min-h-screen bg-gray-50 z-50">
              <Sidebar />
              
              <div className="flex-1 flex flex-col">
                <Header />
                
                <main className="flex-1 ml-64 p-8 ">
                  {children}
                </main>
              </div>
            </div></div>
      </body>
    </html>
  );
}
